LOCATIONS = {
    "airplane": [
        "pilot",
        "flight attendant",
        "passenger",
        "air marshal",
        "co-pilot",
        "flight engineer",
        "stowaway",
    ],
    "beach": [
        "lifeguard",
        "surfer",
        "ice cream vendor",
        "tourist",
        "beach patrol officer",
        "metal detectorist",
        "snorkeling instructor",
        "sunbather",
    ],
    "cathedral": [
        "priest",
        "organist",
        "tourist",
        "restoration artist",
        "bell ringer",
        "choir director",
        "wedding planner",
        "confessor",
    ],
    "corporate party": [
        "CEO",
        "intern",
        "bartender",
        "DJ",
        "board member",
        "caterer",
        "plus-one",
        "janitor",
    ],
    "day spa": [
        "massage therapist",
        "receptionist",
        "nail technician",
        "sauna attendant",
        "yoga instructor",
        "esthetician",
        "manager",
    ],
    "hospital": [
        "surgeon",
        "nurse",
        "patient",
        "paramedic",
        "radiologist",
        "pharmacist",
        "mrsa bacterium",
        "janitor",
    ],
    "military base": [
        "commanding officer",
        "drill sergeant",
        "recruit",
        "medic",
        "intelligence analyst",
        "cook",
        "mechanic",
        "guard",
    ],
    "pirate ship": [
        "captain",
        "first mate",
        "navigator",
        "cook",
        "stowaway",
        "prisoner",
        "lookout",
        "quartermaster",
    ],
    "police station": [
        "detective",
        "police officer",
        "suspect",
        "lawyer",
        "dispatcher",
        "forensic analyst",
        "informant",
    ],
    "bank": [
        "teller",
        "security guard",
        "bank robber",
        "customer",
        "manager",
        "escape car driver",
        "financial advisor",
        "vault technician",
    ],
    "casino": [
        "dealer",
        "high roller",
        "hopeless gambler",
        "bartender",
        "security guard",
        "cashier",
        "entertainer",
    ],
    "circus tent": [
        "ringmaster",
        "acrobat",
        "clown",
        "animal trainer",
        "tightrope walker",
        "fire breather",
        "audience member",
        "stagehand",
    ],
    "cruise ship": [
        "captain",
        "passenger",
        "entertainer",
        "chef",
        "deck hand",
        "tour guide",
        "casino dealer",
        "lifeguard",
    ],
    "embassy": [
        "ambassador",
        "diplomat",
        "security guard",
        "visa applicant",
        "translator",
        "intelligence officer",
        "receptionist",
        "cultural attaché",
    ],
    "hotel": [
        "concierge",
        "bellhop",
        "guest",
        "housekeeper",
        "chef",
        "front desk clerk",
    ],
    "movie studio": [
        "director",
        "actor",
        "camera operator",
        "stunt performer",
        "screenwriter",
        "makeup artist",
        "producer",
    ],
    "passenger train": [
        "conductor",
        "engineer",
        "passenger",
        "dining car server",
        "ticket inspector",
        "stowaway",
        "sleeper car attendant",
        "porter",
    ],
    "polar station": [
        "research scientist",
        "meteorologist",
        "radio operator",
        "cook",
        "expedition leader",
        "medic",
        "maintenance engineer",
    ],
    "restaurant": [
        "head chef",
        "server",
        "food critic",
        "sous chef",
        "host",
        "dishwasher",
        "sommelier",
        "health inspector",
    ],
}
